version: 2.1

locals:
  ignore_prs: &ignore_prs
    branches:
      # Forked pull requests have CIRCLE_BRANCH set to pull/XXX
      ignore: /pull\/[0-9]+/

# reusable 'executor' object for jobs
executors:
  go:
    docker:
      - image: docker.mirror.hashicorp.services/circleci/golang:1.17.5
    environment:
      - TEST_RESULTS: /tmp/test-results # path to where test results are saved

# reusable 'commands' to be added as a step in jobs
commands:
  tf-install:
    description: Install Terraform binary
    parameters:
      version:
        type: string
        default: 0.12.24
      os:
        type: string
        default: linux
      arch:
        type: string
        default: amd64
    steps:
      - run:
          name: download Terraform
          command: |
            curl -L -o /tmp/terraform.zip \
            https://releases.hashicorp.com/terraform/<< parameters.version >>/terraform_<< parameters.version >>_<< parameters.os >>_<< parameters.arch >>.zip
      - run: unzip -d /go/bin /tmp/terraform.zip

  acctest:
    description: Run acceptance tests for cloud providers
    parameters:
      provider-test-infra-dir:
        type: string
      provider-go-test-dir:
        type: string
      provider-go-test-tags:
        type: string
        default: ""
      provider-tf-apply:
        type: string
        default: "terraform apply -auto-approve"
    steps:
      - tf-install
      - checkout

      - when:
          condition:
            equal: [aws, << parameters.provider-test-infra-dir >>]
          steps:
            - run:
                name: download and install AWS CLI
                command: |
                  curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                  echo -e "${AWS_CLI_GPG_KEY}" | gpg --import
                  curl -o awscliv2.sig https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip.sig
                  gpg --verify awscliv2.sig awscliv2.zip
                  unzip awscliv2.zip
                  sudo ./aws/install
            - run:
                name: set assume-role creds
                command: |
                  CREDENTIALS="$(aws sts assume-role --role-arn ${SERVICE_GO_DISCOVER_TESTS_ROLE_ARN} --role-session-name build-${CIRCLE_SHA1} | jq '.Credentials')"
                  echo "export AWS_ACCESS_KEY_ID=$(echo $CREDENTIALS | jq -r '.AccessKeyId')" >> $BASH_ENV
                  echo "export AWS_SECRET_ACCESS_KEY=$(echo $CREDENTIALS | jq -r '.SecretAccessKey')" >> $BASH_ENV
                  echo "export AWS_SESSION_TOKEN=$(echo $CREDENTIALS | jq -r '.SessionToken')" >> $BASH_ENV
      # spin up infrastructure
      - run:
          working_directory: ./test/tf/<< parameters.provider-test-infra-dir >>
          command: terraform init
      - run:
          working_directory: ./test/tf/<< parameters.provider-test-infra-dir >>
          command: << parameters.provider-tf-apply >>

      - run: mkdir -p /tmp/test-results

      # run acceptance tests
      - when:
          condition: << parameters.provider-go-test-tags >>
          steps:
            - run:
                name: Run provider tests
                command: |
                  gotestsum -f standard-verbose --junitfile ${TEST_RESULTS}/results.xml -- \
                    -run << parameters.provider-go-test-tags >> \
                    -v ./provider/<< parameters.provider-go-test-dir >>
      - unless:
          condition: << parameters.provider-go-test-tags >>
          steps:
            - run:
                name: Run provider tests
                command: |
                  gotestsum -f standard-verbose --junitfile ${TEST_RESULTS}/results.xml -- \
                    -v ./provider/<< parameters.provider-go-test-dir >>

      - store_test_results:
          path: /tmp/test-results

      # teardown infrastructure
      - run:
          working_directory: ./test/tf/<< parameters.provider-test-infra-dir >>
          command: terraform destroy --force
          when: always

jobs:
  go-test:
    executor: go
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-test-v1-{{ checksum "go.sum" }}
      - run:
          name: Run go tests
          command: |
            mkdir -p /tmp/test-results
            gotestsum -f standard-verbose --junitfile ${TEST_RESULTS}/results.xml .
      - save_cache:
          key: go-mod-test-v1-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
      - store_test_results:
          path: /tmp/test-results
      - run: go mod download
      - run:
          name: Check go mod tidy
          command: |
            go mod tidy
            git diff --exit-code

  alicloud-provider:
    executor: go
    steps:
      - acctest:
          provider-test-infra-dir: aliyun
          provider-go-test-dir: aliyun
  aws-provider:
    executor: go
    steps:
      - acctest:
          provider-test-infra-dir: aws
          provider-go-test-dir: aws
  azure-vmss-provider:
    executor: go
    steps:
      - acctest:
          provider-test-infra-dir: azure-vmss
          provider-go-test-dir: azure
          provider-go-test-tags: TestVmScaleSetAddrs
  azurerm-provider:
    executor: go
    steps:
      - acctest:
          provider-test-infra-dir: azurerm
          provider-go-test-dir: azure
          provider-go-test-tags: TestTagAddrs
  digitalocean-provider:
    executor: go
    steps:
      - acctest:
          provider-test-infra-dir: digitalocean
          provider-go-test-dir: digitalocean
  gce-provider:
    executor: go
    steps:
      - acctest:
          provider-test-infra-dir: gce
          provider-go-test-dir: gce
  k8s-provider:
    executor: go
    steps:
      - acctest:
          provider-test-infra-dir: k8s
          provider-go-test-dir: k8s
          # We have to apply in two stages because an output of the resource of one provider is then used as the input
          # to the k8s provider. Specifically we are getting auth information from the GKE cluster into the k8s provider.
          # https://www.terraform.io/docs/providers/kubernetes/index.html#stacking-with-managed-kubernetes-cluster-resources
          provider-tf-apply: "terraform apply -target google_container_cluster.cluster -auto-approve && terraform apply -auto-approve"
  packet-provider:
    executor: go
    steps:
      - acctest:
          provider-test-infra-dir: packet
          provider-go-test-dir: packet

  scaleway-provider:
    executor: go
    steps:
      - acctest:
          provider-test-infra-dir: scaleway
          provider-go-test-dir: scaleway
  triton-provider:
    executor: go
    steps:
      - add_ssh_keys:
          fingerprints:
            - "3e:c7:ee:67:a5:e7:bc:eb:be:b8:9a:0e:ee:fb:e2:33"
      - acctest:
          provider-test-infra-dir: triton
          provider-go-test-dir: triton

workflows:
  version: 2
  acceptance:
    jobs:
      - go-test
      - alicloud-provider:
          requires:
            - go-test
          filters: *ignore_prs
      - aws-provider:
          requires:
            - go-test
          filters: *ignore_prs
      - azure-vmss-provider:
          requires:
            - go-test
          filters: *ignore_prs
      - azurerm-provider:
          requires:
            - go-test
          filters: *ignore_prs
      - digitalocean-provider:
          requires:
            - go-test
          filters: *ignore_prs
      - gce-provider:
          requires:
            - go-test
          filters: *ignore_prs
      - k8s-provider:
          requires:
            - go-test
          filters: *ignore_prs
      - packet-provider:
          requires:
            - go-test
          filters: *ignore_prs
      - scaleway-provider:
          requires:
            - go-test
          filters: *ignore_prs
      - triton-provider:
          requires:
            - go-test
          filters: *ignore_prs
